FROM python:3.14

RUN groupadd --gid 10001 product-service && \
    useradd --uid 10001 \
            --gid 10001 \
            --create-home \
            --home-dir /home/produser \
            produser

WORKDIR /product-service

COPY --chown produser:product-service pyproject.toml poetry.lock ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root
    
COPY --chown produser:product-service . .
    
ENV PYTHONPATH=/product-service

RUN poetry run alembic upgrade head

USER produser

CMD ["poetry", "run", "pytest"]