FROM python:3.14

WORKDIR /product-service

COPY pyproject.toml poetry.lock ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root

COPY . .

ENV PYTHONPATH=/product-service

CMD ["poetry", "run", "pytest"]