"""reservation

Revision ID: 0dab25acbd4f
Revises: 1c1b8267a680
Create Date: 2026-09-02 15:36:38.551985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dab25acbd4f'
down_revision: Union[str, Sequence[str], None] = '1c1b8267a680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reserved', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('products', 'quantity',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=18, scale=3),
               existing_nullable=False)
    op.drop_column('products', 'reserved')
    # ### end Alembic commands ###
