"""missed checks

Revision ID: 1c1b8267a680
Revises: e60913061b6f
Create Date: 2026-09-02 09:47:16.473496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1b8267a680'
down_revision: Union[str, Sequence[str], None] = 'e60913061b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.create_check_constraint('check_name_not_empty_ck', 'products', "TRIM(name) <> ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_name_not_empty_ck', 'products', type_='check')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
