"""inv adjustments

Revision ID: dee3fdf3af4e
Revises: 8939aab48c08
Create Date: 2026-09-11 17:24:51.062495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee3fdf3af4e'
down_revision: Union[str, Sequence[str], None] = '8939aab48c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'CANCELLED', name='document_status_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_adjustments_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjustment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_delta != 0', name='non_negative_quantity_ck'),
    sa.ForeignKeyConstraint(['adjustment_id'], ['inventory_adjustments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_adjustments_items')
    op.drop_table('inventory_adjustments')
    # ### end Alembic commands ###
