"""Constraint correction

Revision ID: e60913061b6f
Revises: c60522f3e150
Create Date: 2026-08-31 11:31:23.445636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60913061b6f'
down_revision: Union[str, Sequence[str], None] = 'c60522f3e150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('check_quantity_positive'), 'products', type_='check')
    op.create_check_constraint('check_quantity_non_negative', 'products', 'quantity >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_quantity_non_negative', 'products', type_='check')
    op.create_check_constraint(op.f('check_quantity_positive'), 'products', 'quantity > 0::numeric')
    # ### end Alembic commands ###
