apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-service-db
  labels: 
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-connection-data
                  key: psql_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-connection-data
                  key: psql_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-connection-data
                  key: db_name
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: product-service-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: product-service-db-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

