name: FastAPI CI with PostgreSQL

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: test_db

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'poetry'
          cache-dependency-path: 'product-service/pyproject.toml'

      - name: Configure poetry and install dependencies
        working-directory: ./product-service
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Run pytest
        working-directory: ./product-service
        env:
          DB_SRC: postgresql+asyncpg://postgres:123@localhost:5432/test_db
          TESTING: "True"
        run: pytest